import type { AcademicDetails, ProfessionalDetails, CareerTimelineEntry } from "@/types";

export const mockAcademicDetails: AcademicDetails[] = [
  {
    id: "ac1",
    userId: "u2",
    department: "Computer Science & Engineering",
    degree: "B.E.",
    batchYear: 2018,
    registerNumber: "810817104035",
    createdAt: "2020-06-15T00:00:00Z",
  },
  {
    id: "ac2",
    userId: "u3",
    department: "Electronics & Communication Engineering",
    degree: "B.E.",
    batchYear: 2025,
    registerNumber: "810823205018",
    createdAt: "2023-08-01T00:00:00Z",
  },
  {
    id: "ac3",
    userId: "u7",
    department: "Mechanical Engineering",
    degree: "B.E.",
    batchYear: 2019,
    registerNumber: "810819301022",
    createdAt: "2019-05-20T00:00:00Z",
  },
  {
    id: "ac4",
    userId: "u8",
    department: "Computer Science & Engineering",
    degree: "B.Tech.",
    batchYear: 2018,
    registerNumber: "810818104045",
    createdAt: "2018-06-10T00:00:00Z",
  },
  {
    id: "ac5",
    userId: "u9",
    department: "Information Technology",
    degree: "B.Tech.",
    batchYear: 2021,
    registerNumber: "810821404012",
    createdAt: "2021-03-15T00:00:00Z",
  },
  {
    id: "ac6",
    userId: "u10",
    department: "Computer Science & Engineering",
    degree: "M.E.",
    batchYear: 2017,
    registerNumber: "810817104078",
    createdAt: "2017-11-30T00:00:00Z",
  },
  {
    id: "ac7",
    userId: "u11",
    department: "Electronics & Communication Engineering",
    degree: "B.E.",
    batchYear: 2020,
    registerNumber: "810820205033",
    createdAt: "2020-09-05T00:00:00Z",
  },
  {
    id: "ac8",
    userId: "u12",
    department: "Civil Engineering",
    degree: "B.E.",
    batchYear: 2022,
    registerNumber: "810822102009",
    createdAt: "2022-01-20T00:00:00Z",
  },
  {
    id: "ac9",
    userId: "u13",
    department: "Computer Science & Engineering",
    degree: "B.E.",
    batchYear: 2026,
    registerNumber: "810823104021",
    createdAt: "2023-07-01T00:00:00Z",
  },
  {
    id: "ac10",
    userId: "u14",
    department: "Information Technology",
    degree: "B.Tech.",
    batchYear: 2026,
    registerNumber: "810823404034",
    createdAt: "2023-07-01T00:00:00Z",
  },
];

export const mockProfessionalDetails: ProfessionalDetails[] = [
  {
    id: "pr1",
    userId: "u2",
    currentJobTitle: "Senior Software Engineer",
    companyName: "Zoho Corporation",
    industry: "Information Technology",
    location: "Chennai, Tamil Nadu",
    linkedInUrl: "https://linkedin.com/in/priya-subramanian",
    portfolioUrl: "https://priyasubramanian.dev",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    willingToMentor: true,
    willingToOfferInternship: true,
    createdAt: "2020-06-15T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "pr2",
    userId: "u7",
    currentJobTitle: "Product Manager",
    companyName: "Freshworks",
    industry: "SaaS / Product",
    location: "Chennai, Tamil Nadu",
    linkedInUrl: "https://linkedin.com/in/anitha-murugesan",
    skills: ["Product Strategy", "Agile", "User Research", "Data Analysis"],
    willingToMentor: true,
    willingToOfferInternship: false,
    createdAt: "2019-05-20T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "pr3",
    userId: "u8",
    currentJobTitle: "DevOps Engineer",
    companyName: "Wipro Technologies",
    industry: "Information Technology",
    location: "Bengaluru, Karnataka",
    linkedInUrl: "https://linkedin.com/in/rajesh-pandian",
    skills: ["Docker", "Kubernetes", "Jenkins", "AWS", "Terraform"],
    willingToMentor: false,
    willingToOfferInternship: true,
    createdAt: "2018-06-10T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
  },
  {
    id: "pr4",
    userId: "u9",
    currentJobTitle: "UI/UX Designer",
    companyName: "Infosys",
    industry: "Information Technology",
    location: "Coimbatore, Tamil Nadu",
    linkedInUrl: "https://linkedin.com/in/deepika-chandrasekaran",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping", "CSS"],
    willingToMentor: true,
    willingToOfferInternship: true,
    createdAt: "2021-03-15T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "pr5",
    userId: "u10",
    currentJobTitle: "Data Scientist",
    companyName: "TCS Innovation Labs",
    industry: "Analytics / AI",
    location: "Chennai, Tamil Nadu",
    linkedInUrl: "https://linkedin.com/in/senthil-kumar-p",
    portfolioUrl: "https://senthil-ai.github.io",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "Tableau"],
    willingToMentor: true,
    willingToOfferInternship: true,
    createdAt: "2017-11-30T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "pr6",
    userId: "u11",
    currentJobTitle: "Embedded Systems Engineer",
    companyName: "BOSCH India",
    industry: "Automotive / Embedded",
    location: "Coimbatore, Tamil Nadu",
    skills: ["C", "C++", "ARM Cortex", "RTOS", "CAN Protocol"],
    willingToMentor: false,
    willingToOfferInternship: false,
    createdAt: "2020-09-05T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "pr7",
    userId: "u12",
    currentJobTitle: "Civil Site Engineer",
    companyName: "L&T Construction",
    industry: "Construction / Infrastructure",
    location: "Madurai, Tamil Nadu",
    skills: ["AutoCAD", "Structural Analysis", "Project Management"],
    willingToMentor: true,
    willingToOfferInternship: false,
    createdAt: "2022-01-20T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
];

export const mockCareerTimeline: CareerTimelineEntry[] = [
  {
    id: "ct1",
    userId: "u2",
    jobTitle: "Software Engineer Intern",
    companyName: "Zoho Corporation",
    startDate: "2017-05-01",
    endDate: "2017-11-30",
    description: "Worked on CRM module development using React and Java",
    createdAt: "2020-06-15T00:00:00Z",
  },
  {
    id: "ct2",
    userId: "u2",
    jobTitle: "Junior Software Engineer",
    companyName: "Zoho Corporation",
    startDate: "2018-06-01",
    endDate: "2021-03-31",
    description: "Developed full-stack features for Zoho Books",
    createdAt: "2020-06-15T00:00:00Z",
  },
  {
    id: "ct3",
    userId: "u2",
    jobTitle: "Software Engineer",
    companyName: "Zoho Corporation",
    startDate: "2021-04-01",
    endDate: "2022-12-31",
    description: "Led the migration of legacy systems to microservices architecture",
    createdAt: "2022-01-10T00:00:00Z",
  },
  {
    id: "ct4",
    userId: "u2",
    jobTitle: "Senior Software Engineer",
    companyName: "Zoho Corporation",
    startDate: "2023-01-01",
    description: "Leading a team of 6 engineers, architecting scalable backend systems",
    createdAt: "2023-01-10T00:00:00Z",
  },
  {
    id: "ct5",
    userId: "u10",
    jobTitle: "Data Analyst",
    companyName: "Cognizant",
    startDate: "2017-07-01",
    endDate: "2019-12-31",
    description: "Built BI dashboards using Tableau and Python",
    createdAt: "2017-11-30T00:00:00Z",
  },
  {
    id: "ct6",
    userId: "u10",
    jobTitle: "Senior Data Analyst",
    companyName: "Cognizant",
    startDate: "2020-01-01",
    endDate: "2021-06-30",
    description: "Implemented predictive models for churn analysis",
    createdAt: "2020-01-10T00:00:00Z",
  },
  {
    id: "ct7",
    userId: "u10",
    jobTitle: "Data Scientist",
    companyName: "TCS Innovation Labs",
    startDate: "2021-07-01",
    description: "Working on NLP and computer vision projects for enterprise clients",
    createdAt: "2021-07-05T00:00:00Z",
  },
];
