import type { AlumniUser } from "@/types";

export const mockUsers: AlumniUser[] = [
  {
    id: "u1",
    name: "Arjun Krishnamurthy",
    email: "admin@alumnexus.in",
    password: "admin123",
    role: "ADMIN",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun",
    theme: "dark",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "u2",
    name: "Priya Subramanian",
    email: "alumni@alumnexus.in",
    password: "alumni123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Priya",
    theme: "light",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2020-06-15T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "u3",
    name: "Karthik Selvam",
    email: "student@alumnexus.in",
    password: "student123",
    role: "STUDENT",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Karthik",
    theme: "light",
    emailNotificationsEnabled: false,
    isApproved: true,
    createdAt: "2023-08-01T00:00:00Z",
    updatedAt: "2024-01-20T00:00:00Z",
  },
  {
    id: "u4",
    name: "Meenakshi Rajan",
    email: "employer@alumnexus.in",
    password: "employer123",
    role: "EMPLOYER",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Meenakshi",
    theme: "light",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2022-03-10T00:00:00Z",
    updatedAt: "2024-02-28T00:00:00Z",
  },
  {
    id: "u5",
    name: "Dr. Venkatesh Iyer",
    email: "faculty@alumnexus.in",
    password: "faculty123",
    role: "FACULTY",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Venkatesh",
    theme: "dark",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2018-07-01T00:00:00Z",
    updatedAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "u6",
    name: "Suresh Babu Natarajan",
    email: "superadmin@alumnexus.in",
    password: "super123",
    role: "SUPER_ADMIN",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh",
    theme: "dark",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2017-01-01T00:00:00Z",
    updatedAt: "2024-03-15T00:00:00Z",
  },
  // Additional alumni for directory
  {
    id: "u7",
    name: "Anitha Murugesan",
    email: "anitha.m@gmail.com",
    password: "pass123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Anitha",
    theme: "light",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2019-05-20T00:00:00Z",
    updatedAt: "2024-02-10T00:00:00Z",
  },
  {
    id: "u8",
    name: "Rajesh Pandian",
    email: "rajesh.p@gmail.com",
    password: "pass123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh",
    theme: "light",
    emailNotificationsEnabled: false,
    isApproved: true,
    createdAt: "2018-06-10T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
  },
  {
    id: "u9",
    name: "Deepika Chandrasekaran",
    email: "deepika.c@gmail.com",
    password: "pass123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Deepika",
    theme: "light",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2021-03-15T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "u10",
    name: "Senthil Kumar Palaniappan",
    email: "senthil.k@gmail.com",
    password: "pass123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Senthil",
    theme: "dark",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2017-11-30T00:00:00Z",
    updatedAt: "2024-02-20T00:00:00Z",
  },
  {
    id: "u11",
    name: "Lavanya Gopalakrishnan",
    email: "lavanya.g@gmail.com",
    password: "pass123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lavanya",
    theme: "light",
    emailNotificationsEnabled: false,
    isApproved: true,
    createdAt: "2020-09-05T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "u12",
    name: "Muthu Krishnan",
    email: "muthu.k@gmail.com",
    password: "pass123",
    role: "ALUMNI",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Muthu",
    theme: "dark",
    emailNotificationsEnabled: true,
    isApproved: false,
    createdAt: "2022-01-20T00:00:00Z",
    updatedAt: "2024-03-10T00:00:00Z",
  },
  {
    id: "u13",
    name: "Nithya Saravanan",
    email: "nithya.s@gmail.com",
    password: "pass123",
    role: "STUDENT",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Nithya",
    theme: "light",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2023-07-01T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "u14",
    name: "Arun Balaji",
    email: "arun.b@gmail.com",
    password: "pass123",
    role: "STUDENT",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Arun",
    theme: "light",
    emailNotificationsEnabled: true,
    isApproved: true,
    createdAt: "2023-07-01T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
];

export const getLoginCredentials = () => {
  return [
    { email: "admin@alumnexus.in", password: "admin123", role: "ADMIN", name: "Arjun Krishnamurthy" },
    { email: "alumni@alumnexus.in", password: "alumni123", role: "ALUMNI", name: "Priya Subramanian" },
    { email: "student@alumnexus.in", password: "student123", role: "STUDENT", name: "Karthik Selvam" },
    { email: "employer@alumnexus.in", password: "employer123", role: "EMPLOYER", name: "Meenakshi Rajan" },
    { email: "faculty@alumnexus.in", password: "faculty123", role: "FACULTY", name: "Dr. Venkatesh Iyer" },
    { email: "superadmin@alumnexus.in", password: "super123", role: "SUPER_ADMIN", name: "Suresh Babu Natarajan" },
  ];
};
